name: Documentation Improvement
description: Suggest improvements to documentation, help text, or user guidance
title: "[Docs]: "
labels: ["documentation", "ux"]
body:
  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README file
        - In-app help text
        - Walkthrough/Tutorial
        - Parameter descriptions
        - Theoretical background
        - Code documentation
        - User guide
        - Academic references
        - Installation instructions
        - Other
    validations:
      required: true

  - type: textarea
    id: current_issue
    attributes:
      label: Current Issue
      description: What is unclear, missing, or incorrect in the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
    validations:
      required: true

  - type: dropdown
    id: target_audience
    attributes:
      label: Target Audience
      description: Who would benefit most from this documentation improvement?
      options:
        - New users/students
        - Experienced researchers
        - Educators/instructors
        - Developers
        - All users
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information about this documentation improvement
